-- DQ-AI Setup SQL — App 9 of 10
CREATE DATABASE IF NOT EXISTS DQ_AI; CREATE SCHEMA IF NOT EXISTS DQ_AI.PUBLIC;
USE DATABASE DQ_AI; USE SCHEMA PUBLIC;

-- Target table with DMFs attached
CREATE OR REPLACE TABLE ORDERS (
    ORDER_ID STRING DEFAULT UUID_STRING(), CUSTOMER_ID STRING, ORDER_DATE DATE,
    PRODUCT_ID STRING, AMOUNT FLOAT, STATUS STRING, UPDATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- Quarantine table (same shape)
CREATE OR REPLACE TABLE QUARANTINE_ORDERS (
    ORDER_ID STRING, CUSTOMER_ID STRING, ORDER_DATE DATE,
    PRODUCT_ID STRING, AMOUNT FLOAT, STATUS STRING, UPDATED_AT TIMESTAMP_NTZ,
    QUARANTINED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(), QUARANTINE_REASON STRING
);

-- AI-enriched alert log
CREATE OR REPLACE TABLE DQ_AI_ALERTS (
    ALERT_ID      STRING DEFAULT UUID_STRING() PRIMARY KEY,
    TABLE_NAME    STRING, METRIC_NAME STRING,
    FAILURE_VALUE FLOAT,  AI_EXPLANATION STRING,
    SEVERITY      STRING, ACKNOWLEDGED BOOLEAN DEFAULT FALSE,
    CREATED_AT    TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- Remediation log
CREATE OR REPLACE TABLE REMEDIATION_LOG (
    LOG_ID        STRING DEFAULT UUID_STRING() PRIMARY KEY,
    ACTION        STRING, ROWS_AFFECTED INT,
    REMEDIATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- Custom freshness DMF
CREATE OR REPLACE DATA METRIC FUNCTION FRESHNESS_CHECK(
    arg_t TABLE(UPDATED_AT TIMESTAMP_NTZ)
) RETURNS NUMBER LANGUAGE SQL AS $$
    SELECT CASE WHEN DATEDIFF('hour', MAX(UPDATED_AT), CURRENT_TIMESTAMP()) > 6 THEN 1 ELSE 0 END FROM arg_t
$$;

-- Attach built-in DMFs to ORDERS
ALTER TABLE ORDERS ADD DATA METRIC FUNCTION SNOWFLAKE.CORE.NULL_COUNT
    ON (CUSTOMER_ID) SCHEDULE = 'TRIGGER_ON_CHANGES';
ALTER TABLE ORDERS ADD DATA METRIC FUNCTION SNOWFLAKE.CORE.DUPLICATE_COUNT
    ON (ORDER_ID) SCHEDULE = 'TRIGGER_ON_CHANGES';
ALTER TABLE ORDERS ADD DATA METRIC FUNCTION FRESHNESS_CHECK
    ON (UPDATED_AT) SCHEDULE = 'USING CRON 0 */4 * * * UTC';

-- Auto-remediation task
CREATE OR REPLACE TASK AUTO_REMEDIATE_NULLS
    WAREHOUSE = COMPUTE_WH SCHEDULE = 'USING CRON */15 * * * * UTC'
AS BEGIN
    INSERT INTO QUARANTINE_ORDERS SELECT *, CURRENT_TIMESTAMP(), 'NULL_CUSTOMER_ID'
    FROM ORDERS WHERE CUSTOMER_ID IS NULL;
    DELETE FROM ORDERS WHERE CUSTOMER_ID IS NULL;
    INSERT INTO REMEDIATION_LOG (ACTION, ROWS_AFFECTED)
    SELECT 'QUARANTINE_NULL_CUSTOMER_ID', COUNT(*)
    FROM QUARANTINE_ORDERS WHERE QUARANTINED_AT > DATEADD(minute, -15, CURRENT_TIMESTAMP());
END;
ALTER TASK AUTO_REMEDIATE_NULLS RESUME;

-- AI alert enrichment task (run after DMF evaluations)
CREATE OR REPLACE TASK ENRICH_ALERTS
    WAREHOUSE = COMPUTE_WH SCHEDULE = 'USING CRON 5 * * * * UTC'
AS
INSERT INTO DQ_AI.PUBLIC.DQ_AI_ALERTS (TABLE_NAME, METRIC_NAME, FAILURE_VALUE, AI_EXPLANATION, SEVERITY)
SELECT
    TABLE_NAME, METRIC_NAME, METRIC_VALUE,
    SNOWFLAKE.CORTEX.AI_COMPLETE(
        'claude-sonnet-4-5',
        'Data quality check failed. Explain in 2 sentences what this means and one immediate action. '
        'Table: ' || TABLE_NAME || ' | Check: ' || METRIC_NAME || ' | Value: ' || METRIC_VALUE::STRING,
        {}
    ),
    CASE WHEN METRIC_VALUE > 100 THEN 'CRITICAL' WHEN METRIC_VALUE > 10 THEN 'WARNING' ELSE 'INFO' END
FROM SNOWFLAKE.LOCAL.DATA_QUALITY_MONITORING_RESULTS
WHERE MEASUREMENT_TIME > DATEADD(hour, -1, CURRENT_TIMESTAMP())
  AND METRIC_VALUE > 0
  AND (TABLE_NAME, METRIC_NAME, CAST(MEASUREMENT_TIME AS DATE))
      NOT IN (SELECT TABLE_NAME, METRIC_NAME, CAST(CREATED_AT AS DATE) FROM DQ_AI.PUBLIC.DQ_AI_ALERTS);
ALTER TASK ENRICH_ALERTS RESUME;
