-- NL-BI Setup SQL — App 7 of 10
CREATE DATABASE IF NOT EXISTS NL_BI; CREATE SCHEMA IF NOT EXISTS NL_BI.PUBLIC;
USE DATABASE NL_BI; USE SCHEMA PUBLIC;
CREATE STAGE IF NOT EXISTS ANALYST_STAGE;

CREATE OR REPLACE TABLE ORDERS (
    ORDER_ID STRING DEFAULT UUID_STRING(), ORDER_DATE DATE,
    CUSTOMER_ID STRING, PRODUCT_ID STRING, REGION_ID STRING,
    ORDER_VALUE FLOAT, QUANTITY INT, DISCOUNT_AMOUNT FLOAT DEFAULT 0,
    STATUS STRING DEFAULT 'COMPLETED'
);
CREATE OR REPLACE TABLE PRODUCTS (
    PRODUCT_ID STRING DEFAULT UUID_STRING(), PRODUCT_NAME STRING,
    CATEGORY STRING, UNIT_PRICE FLOAT
);
CREATE OR REPLACE TABLE REGIONS (
    REGION_ID STRING DEFAULT UUID_STRING(), REGION_NAME STRING, COUNTRY STRING
);

-- Seed data
INSERT INTO REGIONS (REGION_ID, REGION_NAME, COUNTRY) VALUES
    ('R001','North America','USA'), ('R002','EMEA','UK'), ('R003','APAC','Singapore');
INSERT INTO PRODUCTS (PRODUCT_ID, PRODUCT_NAME, CATEGORY, UNIT_PRICE) VALUES
    ('P001','Analytics Pro','Software',299), ('P002','Data Connector','Integration',149), ('P003','AI Toolkit','AI/ML',499);
INSERT INTO ORDERS (ORDER_DATE, CUSTOMER_ID, PRODUCT_ID, REGION_ID, ORDER_VALUE, QUANTITY)
SELECT DATEADD(day, -UNIFORM(0,365,RANDOM()), CURRENT_DATE()),
       'CUST_' || UNIFORM(1,50,RANDOM())::STRING, ['P001','P002','P003'][UNIFORM(0,2,RANDOM())::INT],
       ['R001','R002','R003'][UNIFORM(0,2,RANDOM())::INT], UNIFORM(100,2000,RANDOM()), UNIFORM(1,5,RANDOM())
FROM TABLE(GENERATOR(ROWCOUNT => 500));

CREATE OR REPLACE SEMANTIC VIEW SALES_INTELLIGENCE_SV
    TABLES (
        orders   AS NL_BI.PUBLIC.ORDERS   PRIMARY KEY (ORDER_ID),
        products AS NL_BI.PUBLIC.PRODUCTS PRIMARY KEY (PRODUCT_ID),
        regions  AS NL_BI.PUBLIC.REGIONS  PRIMARY KEY (REGION_ID)
    )
    RELATIONSHIPS (
        orders (PRODUCT_ID) REFERENCES products,
        orders (REGION_ID)  REFERENCES regions
    )
    FACTS    (orders.ORDER_VALUE, orders.QUANTITY, orders.DISCOUNT_AMOUNT)
    DIMENSIONS (orders.ORDER_DATE, orders.STATUS,
                products.PRODUCT_NAME, products.CATEGORY,
                regions.REGION_NAME, regions.COUNTRY)
    METRICS  (
        total_revenue   AS SUM(orders.ORDER_VALUE),
        total_orders    AS COUNT(orders.ORDER_ID),
        avg_order_value AS AVG(orders.ORDER_VALUE)
    );
