-- ============================================================
-- Day 11: DCM Project — Task Definitions
-- ============================================================

-- Task: Refresh daily sales aggregation
CREATE OR REPLACE TASK REVENUE_OPS_AI.ANALYTICS.REFRESH_DAILY_SALES_AGG
    WAREHOUSE = COMPUTE_WH
    SCHEDULE = 'USING CRON 0 6 * * * America/New_York'
AS
    MERGE INTO REVENUE_OPS_AI.ANALYTICS.DAILY_SALES_AGG tgt
    USING (
        SELECT
            ORDER_DATE AS AGG_DATE,
            REGION,
            PRODUCT_CATEGORY,
            SUM(TOTAL_AMOUNT) AS TOTAL_REVENUE,
            COUNT(*) AS ORDER_COUNT,
            AVG(DISCOUNT_PCT) AS AVG_DISCOUNT,
            COUNT(CASE WHEN DEAL_STAGE = 'Won' THEN 1 END) AS WON_DEALS,
            COUNT(CASE WHEN DEAL_STAGE = 'Lost' THEN 1 END) AS LOST_DEALS,
            COUNT(CASE WHEN DEAL_STAGE = 'Open' THEN 1 END) AS OPEN_DEALS
        FROM REVENUE_OPS_AI.RAW.SALES_ORDERS
        GROUP BY 1, 2, 3
    ) src
    ON tgt.AGG_DATE = src.AGG_DATE
       AND tgt.REGION = src.REGION
       AND tgt.PRODUCT_CATEGORY = src.PRODUCT_CATEGORY
    WHEN MATCHED THEN UPDATE SET
        TOTAL_REVENUE = src.TOTAL_REVENUE,
        ORDER_COUNT = src.ORDER_COUNT,
        AVG_DISCOUNT = src.AVG_DISCOUNT,
        WON_DEALS = src.WON_DEALS,
        LOST_DEALS = src.LOST_DEALS,
        OPEN_DEALS = src.OPEN_DEALS,
        UPDATED_AT = CURRENT_TIMESTAMP()
    WHEN NOT MATCHED THEN INSERT
        (AGG_DATE, REGION, PRODUCT_CATEGORY, TOTAL_REVENUE, ORDER_COUNT, AVG_DISCOUNT, WON_DEALS, LOST_DEALS, OPEN_DEALS)
        VALUES
        (src.AGG_DATE, src.REGION, src.PRODUCT_CATEGORY, src.TOTAL_REVENUE, src.ORDER_COUNT, src.AVG_DISCOUNT, src.WON_DEALS, src.LOST_DEALS, src.OPEN_DEALS);

-- Task: Refresh customer health snapshot
CREATE OR REPLACE TASK REVENUE_OPS_AI.ANALYTICS.REFRESH_CUSTOMER_HEALTH
    WAREHOUSE = COMPUTE_WH
    AFTER REVENUE_OPS_AI.ANALYTICS.REFRESH_DAILY_SALES_AGG
AS
    MERGE INTO REVENUE_OPS_AI.ANALYTICS.CUSTOMER_HEALTH_SNAPSHOT tgt
    USING (
        SELECT
            CURRENT_DATE() AS SNAPSHOT_DATE,
            CUSTOMER_ID,
            CUSTOMER_NAME,
            HEALTH_STATUS,
            TOTAL_REVENUE,
            AVG_FEEDBACK_RATING AS AVG_RATING,
            OPEN_TICKETS
        FROM REVENUE_OPS_AI.ANALYTICS.CUSTOMER_HEALTH
    ) src
    ON tgt.SNAPSHOT_DATE = src.SNAPSHOT_DATE AND tgt.CUSTOMER_ID = src.CUSTOMER_ID
    WHEN MATCHED THEN UPDATE SET
        HEALTH_STATUS = src.HEALTH_STATUS,
        TOTAL_REVENUE = src.TOTAL_REVENUE,
        AVG_RATING = src.AVG_RATING,
        OPEN_TICKETS = src.OPEN_TICKETS,
        UPDATED_AT = CURRENT_TIMESTAMP()
    WHEN NOT MATCHED THEN INSERT
        (SNAPSHOT_DATE, CUSTOMER_ID, CUSTOMER_NAME, HEALTH_STATUS, TOTAL_REVENUE, AVG_RATING, OPEN_TICKETS)
        VALUES
        (src.SNAPSHOT_DATE, src.CUSTOMER_ID, src.CUSTOMER_NAME, src.HEALTH_STATUS, src.TOTAL_REVENUE, src.AVG_RATING, src.OPEN_TICKETS);
