-- ============================================================
-- Data Metric Functions (DMF) Quality Checks
-- ============================================================
-- Docs: https://docs.snowflake.com/en/user-guide/data-quality-anomaly
-- Requires: Enterprise Edition or higher for anomaly detection

USE SCHEMA REVENUE_OPS_AI.RAW;

-- ============================================================
-- Built-in System DMFs
-- ============================================================

-- 1. Row count check
ALTER TABLE CUSTOMER_FEEDBACK SET DATA_METRIC_SCHEDULE = 'TRIGGER_ON_CHANGES';
ALTER TABLE CUSTOMER_FEEDBACK ADD DATA METRIC FUNCTION SNOWFLAKE.CORE.ROW_COUNT ON ();

ALTER TABLE SALES_ORDERS SET DATA_METRIC_SCHEDULE = 'TRIGGER_ON_CHANGES';
ALTER TABLE SALES_ORDERS ADD DATA METRIC FUNCTION SNOWFLAKE.CORE.ROW_COUNT ON ();

-- 2. Freshness check
ALTER TABLE CUSTOMER_FEEDBACK ADD DATA METRIC FUNCTION SNOWFLAKE.CORE.FRESHNESS ON (INGESTED_AT);
ALTER TABLE SALES_ORDERS ADD DATA METRIC FUNCTION SNOWFLAKE.CORE.FRESHNESS ON (INGESTED_AT);

-- 3. Null count on critical columns
ALTER TABLE SALES_ORDERS ADD DATA METRIC FUNCTION SNOWFLAKE.CORE.NULL_COUNT ON (CUSTOMER_ID);
ALTER TABLE SALES_ORDERS ADD DATA METRIC FUNCTION SNOWFLAKE.CORE.NULL_COUNT ON (ORDER_DATE);
ALTER TABLE SALES_ORDERS ADD DATA METRIC FUNCTION SNOWFLAKE.CORE.NULL_COUNT ON (TOTAL_AMOUNT);

ALTER TABLE CUSTOMER_FEEDBACK ADD DATA METRIC FUNCTION SNOWFLAKE.CORE.NULL_COUNT ON (CUSTOMER_ID);
ALTER TABLE CUSTOMER_FEEDBACK ADD DATA METRIC FUNCTION SNOWFLAKE.CORE.NULL_COUNT ON (FEEDBACK_DATE);

-- 4. Duplicate count
ALTER TABLE SALES_ORDERS ADD DATA METRIC FUNCTION SNOWFLAKE.CORE.DUPLICATE_COUNT ON (ORDER_ID);
ALTER TABLE CUSTOMER_FEEDBACK ADD DATA METRIC FUNCTION SNOWFLAKE.CORE.DUPLICATE_COUNT ON (FEEDBACK_ID);

-- ============================================================
-- Custom DMFs
-- ============================================================

-- Custom: Check that all TOTAL_AMOUNT values are positive
CREATE OR REPLACE DATA METRIC FUNCTION REVENUE_OPS_AI.RAW.NEGATIVE_AMOUNT_COUNT(
    ARG_T TABLE(TOTAL_AMOUNT NUMBER)
)
RETURNS NUMBER
AS
$$
    SELECT COUNT(*) FROM ARG_T WHERE TOTAL_AMOUNT < 0
$$;

ALTER TABLE SALES_ORDERS ADD DATA METRIC FUNCTION REVENUE_OPS_AI.RAW.NEGATIVE_AMOUNT_COUNT ON (TOTAL_AMOUNT);

-- Custom: Check rating values are in valid range (1.0 to 5.0)
CREATE OR REPLACE DATA METRIC FUNCTION REVENUE_OPS_AI.RAW.INVALID_RATING_COUNT(
    ARG_T TABLE(RATING NUMBER)
)
RETURNS NUMBER
AS
$$
    SELECT COUNT(*) FROM ARG_T WHERE RATING < 1.0 OR RATING > 5.0
$$;

ALTER TABLE CUSTOMER_FEEDBACK ADD DATA METRIC FUNCTION REVENUE_OPS_AI.RAW.INVALID_RATING_COUNT ON (RATING);

-- Custom: Orphan check (orders without matching customers)
CREATE OR REPLACE DATA METRIC FUNCTION REVENUE_OPS_AI.RAW.ORPHAN_ORDER_COUNT(
    ARG_T TABLE(CUSTOMER_ID STRING)
)
RETURNS NUMBER
AS
$$
    SELECT COUNT(*)
    FROM ARG_T t
    WHERE NOT EXISTS (
        SELECT 1 FROM REVENUE_OPS_AI.RAW.CUSTOMERS c
        WHERE c.CUSTOMER_ID = t.CUSTOMER_ID
    )
$$;

ALTER TABLE SALES_ORDERS ADD DATA METRIC FUNCTION REVENUE_OPS_AI.RAW.ORPHAN_ORDER_COUNT ON (CUSTOMER_ID);

-- ============================================================
-- Check AI output tables too
-- ============================================================

USE SCHEMA REVENUE_OPS_AI.AI_OUTPUTS;

ALTER TABLE MEDIA_AI_RESULTS SET DATA_METRIC_SCHEDULE = 'TRIGGER_ON_CHANGES';
ALTER TABLE MEDIA_AI_RESULTS ADD DATA METRIC FUNCTION SNOWFLAKE.CORE.ROW_COUNT ON ();
ALTER TABLE MEDIA_AI_RESULTS ADD DATA METRIC FUNCTION SNOWFLAKE.CORE.NULL_COUNT ON (AI_OUTPUT);

-- ============================================================
-- Query DMF results
-- ============================================================
SELECT *
FROM TABLE(INFORMATION_SCHEMA.DATA_METRIC_FUNCTION_REFERENCES(
    REF_ENTITY_NAME => 'REVENUE_OPS_AI.RAW.SALES_ORDERS',
    REF_ENTITY_DOMAIN => 'TABLE'
));

-- View DMF execution history
SELECT *
FROM SNOWFLAKE.LOCAL.DATA_QUALITY_MONITORING_RESULTS
WHERE TABLE_NAME = 'SALES_ORDERS'
ORDER BY MEASUREMENT_TIME DESC
LIMIT 20;
